services:
  php:
    container_name: bax-music
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    user: "${UID}:${GID}"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    container_name: bax-music-mailer-1
    ports:
      - "51479:1025"
      - "51478:8025"

  node:
    image: node:18
    container_name: symfony_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: "tail -f /dev/null"

volumes:
  database_data:
